spring.application.name=airBnbApp

server.port=8081

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnbApp
spring.datasource.username=postgres
spring.datasource.password=Dansat@12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

stripe.secret.key = sk_test_51TANT7KrRF1VbtyJfSXwRqcZ8Zr9AjYE1knSNvZjkDwYQHF2k82UxpLfOlaTKX4VzZZqthqiFujJzORiZmIa4eBb00UnSxqzMB
stripe.webhook.secret = whsec_b2a25e30946807bd9b2861aa440fca0fb425e702008cbd1f67d639277b8c3672

jwt.secretKey = wsehmibzdwh384g03hvehzhg803heperigneinveinguiergb

frontend.url = http://localhost:8081
